apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: healthcareapp
  template:
    metadata:
      labels:
        app: healthcareapp
    spec:
      containers:
        - name: healthcare-container
          image: rahul8897/healthcareapp:1.0
          ports:
            - containerPort: 5000
