apiVersion: v1
kind: Service
metadata:
  name: healthcare-service
spec:
  selector:
    app: healthcareapp
  type: NodePort         
  ports:
    - protocol: TCP
      port: 8080         
      targetPort: 5000   
      nodePort: 30007
